apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: book
  template:
    metadata:
      labels:
        app.kubernetes.io/name: book
    spec:
      containers:
      - image: gcr.io/neogenesis-1/book:v1
        name: book
        ports:
        - containerPort: 8000
        env:
        - name: JAEGER_SERVICE_NAME
          value: book
        - name: JAEGER_AGENT_HOST   # NOTE: Point to the Agent daemon on the Node
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
