apiVersion: apps/v1
kind: Deployment
metadata:
  name: showtime
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: showtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showtime
    spec:
      containers:
      - image: gcr.io/neogenesis-1/showtime:v1
        name: showtime
        ports:
        - containerPort: 8002
        env:
        - name: JAEGER_SERVICE_NAME
          value: showtime
        - name: JAEGER_AGENT_HOST   # NOTE: Point to the Agent daemon on the Node
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
